### PR TITLE
Adding multiprocessing

### PR DESCRIPTION
**Pull request by casabre**
First implementation of multiprocessing for review

### CODE REVIEW

**Comment by casabre** [comment]
@dixudx which formatting tool are you using? I would adapt my changes to this because my VS Code formatted with Black...

**Comment by casabre** [comment]
I observed a speed-up of approximately 43% for a `runSavedQueryByID` call with 82 entries. However, the parsing takes quite long in comparison to the request round-trip time.

- Time with old implementation for the described call `~145 seconds`
- Time with multiprocessing for the described call `~83 seconds`
- The `request.get` takes `~1.5 seconds`

**Review by dixudx — COMMENTED** [review]
Looks good to me.
Would you please format the code? Thanks

**Comment by dixudx** [comment]
> which formatting tool are you using? I would adapt my changes to this because my VS Code formatted with Black...

@casabre  Please run `tox -e pycodestyle`. Refer to the [testing guide](https://github.com/dixudx/rtcclient#testing) for details.

**Comment by dixudx** [comment]
> I observed a speed-up of approximately 43% for a `runSavedQueryByID` call with 82 entries. However, the parsing takes quite long time in comparison to the `requests.get` round-trip time.
> 
>     * Time with old implementation for the described call `~145 seconds`
> 
>     * Time with multiprocessing for the described call `~83 seconds`
> 
>     * The `requests.get` call takes `~1.5 seconds`

Really HUGE improvements. 👍🏻👍🏻👍🏻

I am wondering whether we could have a benchmark graph on our README.

**Comment by casabre** [comment]
> Really HUGE improvements. 👍🏻👍🏻👍🏻

Thanks a lot but I dug deeper because I was wondering about the long overall processing time. I re-used the previous mentioned scenario.

| Action | Processing Time | Comment |
| ------- | ------------------ | ----------- |
| `requests.get` | ~ 1.5 - 2 seconds | Bias via VPN |
| `xmltodict.parse` | ~ 0.1 seconds | |
| process query dict | ~ 85 - 90 seconds | Process spawning takes ~ 5 seconds. Running it in a row uses the instance from garbage collection which speeds up |

I am wondering where the processing time is lost... I don't know any detail about the underlying implementation but is any work item queried separately in the mapping phase? &rarr; #149 could help a lot even without multiprocessing because we can parse during the `await request.get` phase.

> I am wondering whether we could have a benchmark graph on our README.

Sure, we can do. I can prepare a Jupyter notebook. Do you have a reasonable setup? Currently, I am working from home via a VPN connection which biases the results 😉

**Comment by casabre** [comment]
Furthermore, I don't know if json parsing is faster compared to xml parsing. With `ujson` there is a least a fast json implementation available.

**Review by dixudx — APPROVED** [review]
Looks good to me. Thanks for such a HUGE improvement.

**Comment by casabre** [comment]
@dixudx when are you planning a new release? Would need quite soon because Git cloning won't become an option in future :).

**Comment by dixudx** [comment]
@casabre Sure. Already shipped with 0.8.0. You can install with `pip` now.

**Pull request merged**
