### PR TITLE
Improving multiprocessing

### PR DESCRIPTION
**Pull request by casabre**
The previous PR #148 introduced some errors and thus, the commits were reverted. In order to provide multiprocessing functionality, this new PR will be opened.

### CODE REVIEW

**Comment by casabre** [comment]
@dixudx I used your `ThreadPool` implementation and extended it by another `ThreadPool` in the base.py file. Now, it is really fast compared to the previous implementation. I guess, the `ProcessPool` was an overkill regarding spawning up.

**Comment by dixudx** [comment]
All look good to me, except tests for Python 2.7.

Keyword `with` will call `pool.terminate()` (i.e. `__exit__`) automatically , while for Python 2.7 `pool.close()` should be called instead.

@casabre I think we may need a Python decorator to better handle this compatibility.

**Comment by dixudx** [comment]
> We have decided that January 1, 2020, was the day that we sunset Python 2.

I wonder whether we still need to support rtcclient on Python 2.7.

**Comment by casabre** [comment]
> I wonder whether we still need to support rtcclient on Python 2.7.

I just wanted to ask the same. I don't know about the current real utilization of Python 2.7 but it's been a while since its end of life and thus, I would keep the effort low and would make the rtcclient future-proof 😊.

**Comment by casabre** [comment]
@dixudx PR is ready for v0.8.1 😃

**Pull request merged**
