### PR TITLE
Added auth tuple to the get request. Work with 6.0.6.1 and ELM version 7.0

### PR DESCRIPTION
**Pull request by k10blogger**
Hi,
I did this change as in discussion #112 
I have checked this with Jazz 6.0.6.1 and ELM Tool 7.0
This seems to work.
What i dont know whether this would work with the older version of tools. I only have access to the 6.0.6.1 and 7.0

Also i cannot find any documentation to uses the tests in the test folder so i couldnt do it. There seems to be some URL replacement that would be required. If someone can provide me with a clear guideline how to do that i can do that for this change.

### CODE REVIEW

**Comment by oskrdt** [comment]
Is there any plan to get this merged?

**Comment by oskrdt** [comment]
@dixudx could you help us to get this merged?

**Comment by dixudx** [comment]
@oskrdt Could you help verify this PR works as expected? Thx.

**Comment by oskrdt** [comment]
> @oskrdt Could you help verify this PR works as expected? Thx.

It does, I successfully tested as well.

**Comment by oskrdt** [comment]
@dixudx  Is there a plan to release this fix in a new version of the python package?

**Comment by dixudx** [comment]
> @dixudx Is there a plan to release this fix in a new version of the python package?

@oskrdt Yeah, will fire a new release in the next few days.

**Comment by dixudx** [comment]
> @dixudx Is there a plan to release this fix in a new version of the python package?

@oskrdt A new release 0.7.0 has been release. Please install with `pip install rtcclient==0.7.0`.

**Pull request merged**
