### PR TITLE
use ThreadPool for multi-thread

### PR DESCRIPTION
**Pull request by dixudx**

### CODE REVIEW

**Comment by dixudx** [comment]
cc @casabre @MartinBarkerPhilips

**Comment by casabre** [comment]
@dixudx I am wondering why did you revert the multiprocessing changes? I couldn't observe issues like in #151 but I had just around 90 issues compared to 302. Pagination should have worked because they were more than 50 issues.

Furthermore, I would recommend a `ProcessPool` rather than a `ThreadPool` for parsing the workitems because the GIL would limit real parallel computation here. I don't know if we loose any information regarding credentials etc. due to pickling but it worked for me with `pathos` and `lambda` functions.

**Comment by dixudx** [comment]
@casabre sorry for reverting your commits. When I added somes CIs for this projects, the multiprocessing commits failed on many test cases. https://github.com/dixudx/rtcclient/issues/151#issuecomment-1096978649 also had such problems.

> Furthermore, I would recommend a ProcessPool rather than a ThreadPool for parsing the workitems because the GIL would limit real parallel computation here. I don't know if we loose any information regarding credentials etc. due to pickling but it worked for me with pathos and lambda functions.

The pickling error is really a big headache. I've tried using `ProcessPool`, but it is not working.

Using `pathos` is fine, since it uses `dill` that can serialize any objects. But the fact is not like that, the unit tests keep failing.

**Comment by dixudx** [comment]
@casabre I've created another PR #155 using your commits. You can view the CI results against multiple Python versions.

```
_pickle.PicklingError: args[0] from __newobj__ args has the wrong class
```

Lots of pickling errors.

**Comment by casabre** [comment]
@dixudx I understand. **Stability first!** But I am really wondering why it was working out at my setup. I can offer that we can work out a solution together. 
A multiprocess solution could be that we create the credential instance in the sub-process again by just forwarding the credential tuple string &rarr; less objects involved and easy serializing.

**Comment by casabre** [comment]
But you can stick at least with the multi-thread approach in `base.py`. There is just a `ThreadPool` involved which gains also a lot and even more in a sub-process :wink:

**Comment by dixudx** [comment]
> But you can stick at least with the multi-thread approach in base.py. There is just a ThreadPool involved which gains also a lot and even more in a sub-process

**Comment by casabre** [comment]
@dixudx how do you format your code? I am using black as default and as far as I am seeing it, `pycodestyle` just checks for `PEP` compliance.

**Comment by dixudx** [comment]
Please try with

```
yapf --style google --recursive --in-place .
```

to format your codes.

**Comment by MartinBarkerPhilips** [comment]
> cc @casabre @MartinBarkerPhilips

master does not work for be and results in an error ```(Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:997)')))``` because I am running an older version of RTC I believe

**Comment by dixudx** [comment]
@MartinBarkerPhilips What is your Python version?

**Comment by MartinBarkerPhilips** [comment]
> @MartinBarkerPhilips What is your Python version?

I am on Python 3.10.4

**Pull request merged**
